import os
from dotenv import load_dotenv

load_dotenv()

HUGGINGFACE_API_TOKEN=os.getenv("HUGGINGFACE_API_TOKEN")
CHAT_MODEL=os.getenv("CHAT_MODEL")
EMBEDDING_MODEL=os.getenv("EMBEDDING_MODEL")

PINECONE_ENVIRONMENT=os.getenv("PINECONE_ENVIRONMENT")
PINECONE_API_KEY=os.getenv("PINECONE_API_KEY")
PINECONE_INDEX_NAME=os.getenv("PINECONE_INDEX_NAME")
PINECONE_NAMESPACE=os.getenv("PINECONE_NAMESPACE")
UTUBE_API=os.getenv("UTUBE_API")
MONGODB_URI=os.getenv("MONGODB_URI")
MONGODB_CONNECTOR=os.getenv("MONGODB_CONNECTOR")
GEMINI_API_KEY=os.getenv("GEMINI_API_KEY")
GEMINI_EMBEDDING_MODEL=os.getenv("GEMINI_EMBEDDING_MODEL")
GEMINI_CHAT_MODEL=os.getenv("GEMINI_CHAT_MODEL")